package com.accountia.invoice.domain.entity;

import com.accountia.invoice.domain.enums.InvoiceStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLRestriction;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Core entity representing a business invoice.
 *
 * <p>Design decisions:
 * <ul>
 *   <li>UUID primary key (String) — matches frontend's {@code id: string} TypeScript type
 *       and is safe for distributed systems (no auto-increment collisions).</li>
 *   <li>{@code @SQLRestriction("is_deleted = false")} — soft-delete filter applied
 *       automatically to every query; deleted invoices are invisible without a native query.</li>
 *   <li>Recipient is {@code @Embedded} (no join) for read performance.</li>
 *   <li>Line items are {@code @OneToMany} with {@code cascade = ALL, orphanRemoval = true}
 *       so saving/deleting the invoice propagates to its items automatically.</li>
 *   <li>Total amount is stored (not computed at query time) so sorting/filtering by amount
 *       is efficient. It is recalculated in {@link com.accountia.invoice.service.InvoiceService}
 *       every time line items change.</li>
 * </ul>
 */
@Entity
@Table(name = "invoices")
@SQLRestriction("is_deleted = false")   // Hibernate 6.x replacement for @Where
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Invoice extends BaseEntity {

    /** UUID generated by Hibernate — never null, never changes. */
    @Id
    @UuidGenerator
    @Column(name = "id", length = 36, updatable = false, nullable = false)
    private String id;

    /** The business that created this invoice (from JWT businessId claim). */
    @Column(name = "issuer_business_id", nullable = false, length = 36)
    private String issuerBusinessId;

    /**
     * Sequential human-readable number per business (INV-2026-00001).
     * Generated by {@link com.accountia.invoice.service.InvoiceNumberGenerator}.
     */
    @Column(name = "invoice_number", nullable = false, unique = true, length = 30)
    private String invoiceNumber;

    /** Current lifecycle status. Transitions validated by {@code InvoiceStatus.canTransitionTo()}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private InvoiceStatus status;

    /** Sum of all line item amounts (quantity × unitPrice). Kept in sync by the service. */
    @Column(name = "total_amount", nullable = false, precision = 15, scale = 3)
    private BigDecimal totalAmount;

    /**
     * Amount already received (for PARTIAL status).
     * Set via the transition endpoint with {@code amountPaid} payload field.
     */
    @Column(name = "amount_paid", nullable = false, precision = 15, scale = 3)
    private BigDecimal amountPaid;

    /** ISO 4217 currency code (TND, EUR, USD …). */
    @Column(name = "currency", nullable = false, length = 5)
    private String currency;

    /** Date shown on the invoice document. */
    @Column(name = "issued_date", nullable = false)
    private LocalDate issuedDate;

    /** Payment deadline. Overdue job fires when today > dueDate and invoice is not PAID/ARCHIVED. */
    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    /** Timestamp of the most recent status change (displayed in UI). */
    @Column(name = "last_status_change_at")
    private Instant lastStatusChangeAt;

    /** Free-text invoice description shown on the document. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** Payment terms string (e.g. "Net 30", "Due on receipt"). */
    @Column(name = "payment_terms", length = 100)
    private String paymentTerms;

    /**
     * Embedded recipient — stored in this table's columns (no JOIN needed).
     * @see InvoiceRecipient
     */
    @Embedded
    private InvoiceRecipient recipient;

    /**
     * Child line items — fetched LAZILY (only when accessed).
     * {@code cascade = ALL} means: save invoice → save items.
     * {@code orphanRemoval = true} means: remove item from list → delete from DB.
     */
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("sortOrder ASC")
    @Builder.Default
    private List<InvoiceLineItem> lineItems = new ArrayList<>();

    // ── Soft delete ───────────────────────────────────────────────────────────

    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private boolean deleted = false;

    @Column(name = "deleted_at")
    private Instant deletedAt;

    // ── Helper methods ────────────────────────────────────────────────────────

    /**
     * Adds a line item and sets its back-reference to this invoice.
     * Always use this method instead of {@code getLineItems().add(item)}.
     */
    public void addLineItem(InvoiceLineItem item) {
        item.setInvoice(this);
        lineItems.add(item);
    }

    /**
     * Replaces all line items atomically (clears old ones, adds new ones).
     * orphanRemoval=true ensures the old items are deleted from the database.
     */
    public void replaceLineItems(List<InvoiceLineItem> newItems) {
        lineItems.clear();
        newItems.forEach(this::addLineItem);
    }

    /**
     * Recalculates {@code totalAmount} by summing all line items.
     * Called by the service layer after any line item change.
     */
    public void recalculateTotals() {
        this.totalAmount = lineItems.stream()
                .map(InvoiceLineItem::getAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
}
