server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${EUREKA_USER_NAME:admin}
      password: ${EUREKA_USER_PASSWORD:}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}
    eviction-interval-timer-in-ms: ${EUREKA_EVICTION_INTERVAL:5000}
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: ${LOG_LEVEL_EUREKA:INFO}
    com.netflix.discovery: ${LOG_LEVEL_DISCOVERY:INFO}
