# Business Microservice Configuration
server:
  port: 8080

spring:
  application:
    name: business-ms

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: business-ms
    non-secure-port: 8080
    secure-port-enabled: false
