# Invoice Microservice Configuration
server:
  port: 8083

spring:
  application:
    name: invoice-ms
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/accountia/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/accountia}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: invoice-ms
    non-secure-port: 8083
    secure-port-enabled: false
