package com.accountia.invoice.dto.response;

import java.time.LocalDate;
import java.util.List;

/**
 * AI-powered payment prediction for a specific invoice.
 *
 * <p>Returned by {@code GET /invoices/{id}/ai/payment-prediction}.
 * When the OpenAI API is unavailable, all fields are still populated
 * using rule-based logic and {@code aiEnhanced} is set to {@code false}.
 */
public record AiPaymentPredictionResponse(

        String invoiceId,

        /** Probability breakdown in percentages (must sum to 100). */
        PaymentProbability paymentProbability,

        /** Estimated payment date based on client history. */
        LocalDate predictedPaymentDate,

        /** LOW | MEDIUM | HIGH */
        String riskLevel,

        /** Key factors (positive and negative) used to compute the score. */
        List<String> riskFactors,

        /** Natural-language summary and recommended actions (AI-generated or rule-based). */
        String recommendation,

        /**
         * Overall payment reliability score for this client (0–100).
         * Higher = more reliable.
         */
        int clientPaymentScore,

        /** True when the recommendation was generated by AI; false = rules only. */
        boolean aiEnhanced
) {
    /** Nested record for on-time / late / unpaid probabilities. */
    public record PaymentProbability(int onTime, int late, int unpaid) {}
}
